LonL=10.8;LatL=33.75;
    ColGlob=linspace(45,39,10); % Salinite
    ColGlob=linspace(27.,26.5,10); % Température
    ColGlob=linspace(2.,0,10); % Fluorimetrie
    ColGlob=linspace(0.5,0,10); % Turbidite
    Col=ColGlob;
    R=0;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.1;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.2;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.3;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.4;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.5;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.6;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.7;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.8;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=0.9;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])
    R=1;
    hold on,plot(LonL,LatL,'.k','MarkerSize',24,'Color',[1-R 0 R])

      legend(...
           ['Eau : profondeur : 20m' ],...
           ['Eau : faible profondeur'], ...
           [''], ...
           ['Terre'], ...
           ['>' num2str(Col(1))],...
           ['>' num2str(Col(2))], ...
           ['>' num2str(Col(3))], ...
           ['>' num2str(Col(4))], ...
           ['>' num2str(Col(5))], ...
           ['>' num2str(Col(6))], ...
           ['>' num2str(Col(7))], ...
           ['>' num2str(Col(8))], ...
           ['>' num2str(Col(9))], ...
           ['>' num2str(Col(10))], ...
           'location','EastOutside')

  